cloud:
  aws:
    s3:
      bucket: ${SPRING_AWS_BUCKET}
      path:
        image: image
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${SPRING_AWS_ACCESS_KEY}
      secretKey: ${SPRING_AWS_SECRET_KEY}